package gov.nih.nci.caintegrator.application.mail;

import org.apache.commons.validator.EmailValidator;

public class MailProps {

	public String mailTo;
	public String mailFrom;
	public String body;
	public String subject;
	public String smtp;
	//this such as IP, username, and date are to be part of the body, generated by each app as to stay generic
	//can add others for special ops: cc, bcc, header, mime, etc
	public MailProps(String t, String f, String b, String s, String smtp)	{
		this.setMailFrom(f);
		this.setMailTo(t);
		this.setBody(b);
		this.setSmtp(smtp);
		this.setSubject(s);
	}
	
	public MailProps(){}
	
	public String getBody() {
		return body;
	}
	public void setBody(String body) {
		this.body = body;
	}
	public String getMailFrom() {
		return mailFrom;
	}
	public void setMailFrom(String mailFrom) {
		this.mailFrom = EmailValidator.getInstance().isValid(mailFrom) ? mailFrom : null;
	}
	public String getMailTo() {
		return mailTo;
	}
	public void setMailTo(String mailTo) {
		this.mailTo = EmailValidator.getInstance().isValid(mailTo) ? mailTo : null;
	}
	public String getSmtp() {
		return smtp;
	}
	public void setSmtp(String smtp) {
		this.smtp = smtp;
	}
	public String getSubject() {
		return subject;
	}
	public void setSubject(String subject) {
		this.subject = subject;
	}
}
